In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [11]:
#just testing what they use in matplotlib
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [82]:
a = np.array([1,2,3,4])
b = np.array([ [1 for i in range(4)],[(0 if i%2==0 else 1) for i in range(4)] ]).reshape(4,2)
a @ b, a, b

(array([ 3, 10]),
 array([1, 2, 3, 4]),
 array([[1, 1],
        [1, 1],
        [0, 1],
        [0, 1]]))

In [561]:
x = np.array([1,2,3,2.5]).reshape(1,x.shape[1])
#weights = [ [.2,.8,-0.5,1],[0.5,-0.91,.26,-.5],[-0.26,-0.27,.17,.87] ]
biases = [2,3,.5]
y = np.array(1).reshape(1,1)

theta = np.random.rand(1,3)
theta

# matrix for generalisation 
x

#np.dot will convert list to arrays before multiplication

array([[1. , 2. , 3. , 2.5]])

In [67]:
?np.maximum
# append after comparing maximum between 0 and 1 for each element
np.maximum(0,weights),np.array(weights)

(array([[0.2 , 0.8 , 0.  , 1.  ],
        [0.5 , 0.  , 0.26, 0.  ],
        [0.  , 0.  , 0.17, 0.87]]),
 array([[ 0.2 ,  0.8 , -0.5 ,  1.  ],
        [ 0.5 , -0.91,  0.26, -0.5 ],
        [-0.26, -0.27,  0.17,  0.87]]))

Call signature:  np.maximum(*args, **kwargs)
Type:            ufunc
String form:     <ufunc 'maximum'>
File:            c:\users\zouru\anaconda3\lib\site-packages\numpy\__init__.py
Docstring:      
maximum(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Element-wise maximum of array elements.

Compare two arrays and returns a new array containing the element-wise
maxima. If one of the elements being compared is a NaN, then that
element is returned. If both elements are NaNs then the first is
returned. The latter distinction is important for complex NaNs, which
are defined as at least one of the real or imaginary parts being a NaN.
The net effect is that NaNs are propagated.

Parameters
----------
x1, x2 : array_like
    The arrays holding the elements to be compared. If ``x1.shape != x2.shape``, they must be broadcastable to a common shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray 

In [337]:
#debugger
def printer(*args):
    all = ''
    for i in args:
        all += f"{i},shape : {i.shape if isinstance(i,np.ndarray) else 'this is not np.array'}"
    print(all)


[[0.23253709]],shape : (1, 1)


In [599]:
#dense layer is just another regular layer in a neural network

def a_h(x,weight):
    return x @ weight.T

def sigmoid(z):
    return 1/(1+np.exp(-z))

def nn_size(m,n_neurons):
    return np.random.rand( m ,n_neurons)
    

#all kept within a single function to reuse variables & values

#instantiate random weights


w0 = np.array(np.random.rand(1,4))
' neural network weights dim is  no. features * no. neurons next layer '
weights = nn_size( x.shape[1] ,4)


def forward(x,n_neurons_next,weights,*w0):
    #no. of entries x no. of features
    m,n = x.shape[0],x.shape[1]

    # include bias
    bias = np.ones(( m,n_neurons_next )).reshape( m,n_neurons_next )
    
    #accounting for first layer missing w0, function reuse in backprop
    ' size should be x.shape[1] which is number of neurons in existing layer to fit bias to every single neuron '

    if not w0:
        w0 = np.random.rand(1,n_neurons_next)
    else:
        w0=w0[0]

    

    # activation of the next layer, there are n_neurons , thus n_neuron activations (h(x))
    #relu it instead of sigmoid
    #print('bias and w0'),printer(bias,w0)

    a_h(bias, w0)
    
    a1 =  sigmoid( a_h(x,weights)   )


    #weights including bias


    ' correct,  multiplying one theta0 weight (by column) per row'
    weights = np.vstack( (w0,weights.reshape(m,n_neurons_next)) )
    ' weights dim n*nn+1 ; n is number of features , nn is number of neurons per layer'

    #print(f'a1 is {a1}!!!')
    return a1,weights


def a_Relu(inputs):
    return np.maximum(0,inputs)

# optimiser Adam, Daniel

In [602]:
gradDesc(x,y,weights,0.001,100,[4,1])

lda3


(array([[-0.23666636]]), array([[-0.05591689, -0.04280603]]))

In [455]:
#nn_size(4,4)
#print(w0.shape,'w0',x.shape[1])
#print( np.hstack( (w0.reshape(1,1),weights) ) )

a1,w1 = forward(x,4,weights,w0)
#returns layer 1 activation and weights theta(1)
printer(a1,w1)
# hypothesis for layer 1, 4 neurons
# dim should be m*1

[[1.  2.  3.  2.5]],shape : (1, 4)[[0.04157263 0.36032791 0.55802922 0.35554947]
 [0.60620643 0.14641091 0.03041007 0.12524438]
 [0.30373598 0.59231388 0.89458624 0.42280472]
 [0.72209978 0.99760761 0.40823771 0.88956193]],shape : (4, 4)
[[0.96528293 0.7864015  0.99467039 0.99790464]],shape : (1, 4)[[0.27924801 0.07293734 0.63204093 0.40579998]
 [0.04157263 0.36032791 0.55802922 0.35554947]
 [0.60620643 0.14641091 0.03041007 0.12524438]
 [0.30373598 0.59231388 0.89458624 0.42280472]
 [0.72209978 0.99760761 0.40823771 0.88956193]],shape : (5, 4)


In [601]:
#print(f'weight is {weights}') 

def cost(x,y,weights):
    m = x.shape[0]
    return 1/m * np.sum( np.sum( y* np.log( sigmoid(a_h(x,weights))) + (1-y)*np.log(1-sigmoid (a_h(x,weights)) ) ) )


def gradDesc(x,y,weights,alpha,iter,layers):
    m,n = x.shape[0], x.shape[1]

    # including bias
    ' weights param must include weights for bias unit ! '

    n1,n2= layers[0],layers[1]

    # activation and weights with bias weights
    a1,w1 = forward(x,n1,nn_size(m,n1))

    # weights supposed to be (no. of features * no. neurons next layer)
    a2,w2= forward(a1, n2 , nn_size(n2,n2) )
    'nn_size(a,b) , whereby a=no. of features in existing layer, b is no. of features in next' 

    # backprop
    print('lda3')
    lda3 = a2 -y
    lda2 = a_h(lda3,w2)*( a2*(1-a2) )   #broadcast

    #merge into matrix

    # set deriv to 0
    djd0 = 0
    djdi = 0


    #all the derivatives
    djd0 = a_h(a2,lda3) 
    djdi = a_h(a1,lda2.T)

    ''' a for loop with number of iter is to accumulate terms on each iter and perform gradient descent 
    '''

    # djd0 = 1/m * djd0
    # djdi = 1/m * djdi

    return djd0,djdi


In [207]:
a_h(x,weights), ( (1-y) * np.log( 1-a_Relu(a_h(x,weights)) )), a_h(x,weights) + ( (1-y) * np.log( 1-a_Relu(a_h(x,weights)) ))

(array([[4.72080193]]), array([[nan]]), array([[nan]]))

In [592]:
gradDesc(x,y,weights,0.001,100,[4,1])

weights
[[0.85219858 0.94004272 0.49363345 0.61497112]],shape : (1, 4)[[0.00727035 0.84417149 0.42559869 0.94652051]],shape : (1, 4)
 m is 1 nn is 4,weight shape is (2, 4) weights is [[0.85219858 0.94004272 0.49363345 0.61497112]
 [0.00727035 0.84417149 0.42559869 0.94652051]]
weights
[[0.60493919]],shape : (1, 1)[[0.96565247]],shape : (1, 1)
 m is 1 nn is 1,weight shape is (2, 1) weights is [[0.60493919]
 [0.96565247]]
lda3


(array([[-0.20012394]]), array([[-0.03333444, -0.0532111 ]]))

In [454]:
x,y,weights

(array([[1. , 2. , 3. , 2.5]]),
 array([[1]]),
 array([[0.04157263, 0.36032791, 0.55802922, 0.35554947],
        [0.60620643, 0.14641091, 0.03041007, 0.12524438],
        [0.30373598, 0.59231388, 0.89458624, 0.42280472],
        [0.72209978, 0.99760761, 0.40823771, 0.88956193]]))